version: "3.9"

services:
  nginx:
    image: rotman-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile

  web:
    image: rotman
    build: .
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"

  ingress:
    # Pulled Feb 16, 2023
    image: nginx@sha256:6650513efd1d27c1f8a5351cbd33edf85cc7e0d9d0fcb4ffb23d8fa89b601ba8
    volumes:
      - ./ingress-nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - nginx
      - web
