name: CI
on:
  push:
    paths:
      - 'rotman/**'
      - '.github/workflows/rotman.yml'
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_APP_IMAGE_NAME: "ghcr.io/orihoch/chatgptgames/rotman"
        DOCKER_NGINX_IMAGE_NAME: "ghcr.io/orihoch/chatgptgames/rotman-nginx"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_BUILD_PATH: "rotman"
      run: |
        echo "${GITHUB_TOKEN}" | docker login ghcr.io -u orihoch --password-stdin &&\
        if docker pull "${DOCKER_APP_IMAGE_NAME}:latest"; then
          CACHE_FROM_ARG="--cache-from ${DOCKER_APP_IMAGE_NAME}:latest"
        else
          CACHE_FROM_ARG=""
        fi &&\
        docker build $CACHE_FROM_ARG --build-arg VERSION=${GITHUB_SHA} -t app $DOCKER_BUILD_PATH &&\
        docker tag app "${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}" &&\
        docker push "${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}" &&\
        if docker pull "${DOCKER_NGINX_IMAGE_NAME}:latest"; then
          CACHE_FROM_ARG="--cache-from ${DOCKER_NGINX_IMAGE_NAME}:latest"
        else
          CACHE_FROM_ARG=""
        fi &&\
        docker build $CACHE_FROM_ARG --build-arg VERSION=${GITHUB_SHA} -t nginx $DOCKER_BUILD_PATH &&\
        docker tag nginx "${DOCKER_NGINX_IMAGE_NAME}:${GITHUB_SHA}" &&\
        docker push "${DOCKER_NGINX_IMAGE_NAME}:${GITHUB_SHA}" &&\
        if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
          docker tag app "${DOCKER_APP_IMAGE_NAME}:latest" &&\
          docker push "${DOCKER_APP_IMAGE_NAME}:latest" &&\
          docker tag nginx "${DOCKER_NGINX_IMAGE_NAME}:latest" &&\
          docker push "${DOCKER_NGINX_IMAGE_NAME}:latest"
        fi
